### ISSUE TITLE
2 servers can still run the same job at the same time

### ISSUE THREAD

**Issue by WayneUong** [percolatestudio/meteor-synced-cron#141]
I setup so 2 meteor apps sharing the same database. And most of the times, both apps can still run the same job at the same time. This package doesn't prevent the second server from starting the same job if the other server is not done.

**Comment by TheGame2500** [comment]
@WayneUong are you sure you are using littledata:synced-cron and note percolatestudio:synced-cron? There's been a migration at some point and percolatestudio:synced-cron is not maintained anymore. Seems like you're encountering the issue solved by https://github.com/percolatestudio/meteor-synced-cron/pull/135

**Comment by WayneUong** [comment]
@TheGame2500 I did a quick test to confirm:

```
if (Meteor.isServer) {
    SyncedCron.add({
        name: 'Test',
        schedule: function (parser) {
            return parser.text('every 5 seconds');
        },
        job: function () {
            console.log('start');
            Meteor._sleepForMs(9999999);
            console.log('end')
        }
    });

    Meteor.startup(() => SyncedCron.start());
}
```

I have the first server running, let the cron job starts, then start the 2nd server, sharing the same db using `MONGO_URL=mongodb://localhost:3001/meteor meteor --port 3002`

The result is that the 2nd server starts the same job while the 1st is still not done. `Meteor._sleepForMs(9999999);` is to simulate a long running cron job.

<img width="1619" alt="Screen Shot 2019-12-04 at 10 10 30 AM" src="https://user-images.githubusercontent.com/8436742/70168914-a0f01380-167e-11ea-86f7-578e93450475.png">

**Comment by WayneUong** [comment]
@TheGame2500 Can you reproduce it?
